apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: akvprovider-demo
  namespace: test
spec:
  provider: azure
  secretObjects:
  - data:
    - key: secret1
      objectName: secret1
    secretName: secret1
    type: Opaque
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: aro-ps-keyvault
    objects:  |
      array:
        - |
          objectName: secret1
          objectType: secret
          objectVersion: ""
    tenantId: xxxx-yyyy
